apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rossmann-api-monitor
  namespace: monitoring
  labels:
    release: prom
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: rossmann-api
  endpoints:
    - port: http
      interval: 1s
      path: /metrics
